[colors.bright]
black = "0x4a697d"
blue = "0x2ca2f5"
cyan = "0x33c5ba"
green = "0xa4bd00"
magenta = "0x8086e8"
red = "0xfa3935"
white = "0xfdf6e3"
yellow = "0xd9a400"

[colors.cursor]
cursor = "0xafbfbf"
text = "0x000000"

[colors.normal]
black = "0x263640"
blue = "0x2587cc"
cyan = "0x289c93"
green = "0x819400"
magenta = "0x696ebf"
red = "0xd12f2c"
white = "0xbfbaac"
yellow = "0xb08500"

[colors.primary]
background = "0x141c21"
foreground = "0xfcfcfc"

[font]
size = 11.0

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u0002\u001B[D"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002\u001B[C"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002\u001B[B"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002\u001B[A"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"

[schemes.breeze.bright]
black = "0x7f8c8d"
blue = "0x3daee9"
cyan = "0x16a085"
green = "0x03C03C"
magenta = "0x8e44ad"
red = "0xc0392b"
white = "0xffffff"
yellow = "0xfdbc4b"

[schemes.breeze.dim]
black = "0x31363b"
blue = "0x1b668f"
cyan = "0x186c60"
green = "0x17a262"
magenta = "0x614a73"
red = "0x783228"
white = "0x63686d"
yellow = "0xb65619"

[schemes.breeze.normal]
black = "0x232627"
blue = "0x1d99f3"
cyan = "0x1abc9c"
green = "0x009F6B"
magenta = "0x9b59b6"
red = "0xed1515"
white = "0xfcfcfc"
yellow = "0xf67400"

[schemes.breeze.primary]
background = "0x141c21"
foreground = "0xfcfcfc"

[schemes.onehalflight.bright]
black = "0x383a42"
blue = "0x0184bc"
cyan = "0x0997b3"
green = "0x50a14f"
magenta = "0xa626a4"
red = "0xe45649"
white = "0xfafafa"
yellow = "0xc18401"

[schemes.onehalflight.normal]
black = "0x383a42"
blue = "0x0184bc"
cyan = "0x0997b3"
green = "0x50a14f"
magenta = "0xa626a4"
red = "0xe45649"
white = "0xfafafa"
yellow = "0xc18401"

[schemes.onehalflight.primary]
background = "0xfafafa"
foreground = "0x383a42"

[schemes.papertheme.bright]
black = "#555555"
blue = "#1E6FCC"
cyan = "#158C86"
green = "#216609"
magenta = "#5C21A5"
red = "#CC3E28"
white = "#AAAAAA"
yellow = "#B58900"

[schemes.papertheme.normal]
black = "#000000"
blue = "#1E6FCC"
cyan = "#158C86"
green = "#216609"
magenta = "#5C21A5"
red = "#CC3E28"
white = "#AAAAAA"
yellow = "#B58900"

[schemes.papertheme.primary]
background = "#F2EEDE"
foreground = "#000000"

[schemes.solarized.bright]
black = "0x4a697d"
blue = "0x2ca2f5"
cyan = "0x33c5ba"
green = "0xa4bd00"
magenta = "0x8086e8"
red = "0xfa3935"
white = "0xfdf6e3"
yellow = "0xd9a400"

[schemes.solarized.cursor]
cursor = "0xafbfbf"
text = "0x000000"

[schemes.solarized.normal]
black = "0x263640"
blue = "0x2587cc"
cyan = "0x289c93"
green = "0x819400"
magenta = "0x696ebf"
red = "0xd12f2c"
white = "0xbfbaac"
yellow = "0xb08500"

[schemes.solarized.primary]
background = "0x141c21"
foreground = "0xfcfcfc"

[schemes.solarizedlight.bright]
black = "0x002b36"
blue = "0x839496"
cyan = "0x93a1a1"
green = "0x586e75"
magenta = "0x6c71c4"
red = "0xcb4b16"
white = "0xfdf6e3"
yellow = "0x657b83"

[schemes.solarizedlight.cursor]
cursor = "0xafbfbf"
text = "0x000000"

[schemes.solarizedlight.normal]
black = "0x073642"
blue = "0x268bd2"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0xd33682"
red = "0xdc322f"
white = "0xeee8d5"
yellow = "0xb58900"

[schemes.solarizedlight.primary]
background = "0xfdf6e3"
foreground = "0x586e75"

[scrolling]
history = 10000

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.92

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10
