[[language]]
name = "rust"
auto-format = true
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
language-server = { command = "rustup", args = ["run", "stable", "rust-analyzer"] }
